# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

#FIXME see https://github.com/inveniosoftware/invenio-access/issues/129
dist: trusty

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis-server

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" DEPLOY=true
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "3.6"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio; GRANT ALL ON invenio.* TO 'root';' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "WUU11aLRd9ttsk+pvnXJu6Kq4cXhgcjT0UcDMQ1rtOZg+FulHOXMEKqPiHWZxob01hmRkYKHGF0yM6kEE1cvTP2dSPC91YVwQvANmoV9TUXU35vEOlY4iOcZhfKGzM67Sx7Idh78ildCSm834+nP7iTB60TtNqxWDn839S9GpvHxyJLwblOkYxZWIrlGJ2dE41NxjGUDnmU/Js8s+yCORN1ckkIMGbO2ZkSCqwmWj+DhceEz9JBgeEyO5x2Zp0uqaUtM4gnUA+dkWqAhwLvwtsLvI7zF5ihHZGYEeHdRdEG8J43t+2MieTq+LkAh+mggTrfP5BeCnA0kATCuHeIYycgXVOX8fCaH789x9dsIkWXHGXsFz9Qb7pYKUCQZXOhMwCecaM4mXspIHjl1GZZx5FBQ3hkZu/ogIoAUmjd8q1gLi5oq+ZNIExXoPuzRnXQT5/qTapV+c+r7w1BIOX03Z2+RxyDCZsdIiICAYzAv5kQjFqyTB9nosNFuDyn1ZZIHWXCZ8lAJnbTj/ha3cafH1957K/r6RItl+rEpZCT0DnaG0ChBqdqqze33/+L45Bp95ALA+nEB1FcyqVGFTl8J68YFBHGeW7U+IvwuC16S03cRGbe0s1xtcxilshT27PnyBERyM9r1Ub61QytlOt6a9FlVbxpgCIbffhWxfAbjHBw="
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $DEPLOY = true
