# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite
    - env: REQUIREMENTS=devel DB=mysql EXTRAS=all,mysql
    - env: REQUIREMENTS=devel DB=psql EXTRAS=all,postgresql
    - python: 3.8

cache:
  - pip

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
  matrix:
    - REQUIREMENTS=lowest EXTRAS=all,sqlite
    - REQUIREMENTS=lowest DB=mysql EXTRAS=all,mysql
    - REQUIREMENTS=lowest DB=psql EXTRAS=all,postgresql
    - REQUIREMENTS=release EXTRAS=all,sqlite
    - REQUIREMENTS=release DB=mysql EXTRAS=all,mysql
    - REQUIREMENTS=release DB=psql EXTRAS=all,postgresql DEPLOY=true

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - "pip uninstall -y six"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "docker --version"
  - "docker-compose --version"
install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "WUU11aLRd9ttsk+pvnXJu6Kq4cXhgcjT0UcDMQ1rtOZg+FulHOXMEKqPiHWZxob01hmRkYKHGF0yM6kEE1cvTP2dSPC91YVwQvANmoV9TUXU35vEOlY4iOcZhfKGzM67Sx7Idh78ildCSm834+nP7iTB60TtNqxWDn839S9GpvHxyJLwblOkYxZWIrlGJ2dE41NxjGUDnmU/Js8s+yCORN1ckkIMGbO2ZkSCqwmWj+DhceEz9JBgeEyO5x2Zp0uqaUtM4gnUA+dkWqAhwLvwtsLvI7zF5ihHZGYEeHdRdEG8J43t+2MieTq+LkAh+mggTrfP5BeCnA0kATCuHeIYycgXVOX8fCaH789x9dsIkWXHGXsFz9Qb7pYKUCQZXOhMwCecaM4mXspIHjl1GZZx5FBQ3hkZu/ogIoAUmjd8q1gLi5oq+ZNIExXoPuzRnXQT5/qTapV+c+r7w1BIOX03Z2+RxyDCZsdIiICAYzAv5kQjFqyTB9nosNFuDyn1ZZIHWXCZ8lAJnbTj/ha3cafH1957K/r6RItl+rEpZCT0DnaG0ChBqdqqze33/+L45Bp95ALA+nEB1FcyqVGFTl8J68YFBHGeW7U+IvwuC16S03cRGbe0s1xtcxilshT27PnyBERyM9r1Ub61QytlOt6a9FlVbxpgCIbffhWxfAbjHBw="
  distributions: "compile_catalog sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    python: "3.6"
    condition: $DEPLOY = true
